package model;

// Generated 26-feb-2015 17:12:36 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

    private int idAnswer;
    private Question question;
    private String answerText;
    private Boolean isCorrect;
    private Set users = new HashSet(0);

    public Answer() {
    }

    public Answer(int idAnswer, Question question) {
	this.idAnswer = idAnswer;
	this.question = question;
    }

    public Answer(int idAnswer, Question question, String answerText,
	    Boolean isCorrect, Set users) {
	this.idAnswer = idAnswer;
	this.question = question;
	this.answerText = answerText;
	this.isCorrect = isCorrect;
	this.users = users;
    }

    public int getIdAnswer() {
	return this.idAnswer;
    }

    public void setIdAnswer(int idAnswer) {
	this.idAnswer = idAnswer;
    }

    public Question getQuestion() {
	return this.question;
    }

    public void setQuestion(Question question) {
	this.question = question;
    }

    public String getAnswerText() {
	return this.answerText;
    }

    public void setAnswerText(String answerText) {
	this.answerText = answerText;
    }

    public Boolean getIsCorrect() {
	return this.isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
	this.isCorrect = isCorrect;
    }

    public Set getUsers() {
	return this.users;
    }

    public void setUsers(Set users) {
	this.users = users;
    }

}
