package model;

// Generated 18-feb-2015 18:33:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int id;
    private String name;
    private String email;
    private Set answers = new HashSet(0);
    private Set tests = new HashSet(0);

    public User() {
    }

    public User(int id) {
	this.id = id;
    }

    public User(int id, String name, String email, Set answers, Set tests) {
	this.id = id;
	this.name = name;
	this.email = email;
	this.answers = answers;
	this.tests = tests;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public Set getAnswers() {
	return this.answers;
    }

    public void setAnswers(Set answers) {
	this.answers = answers;
    }

    public Set getTests() {
	return this.tests;
    }

    public void setTests(Set tests) {
	this.tests = tests;
    }

}
